# Generated by Django 4.2.3 on 2023-07-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accnum', models.CharField(max_length=20)),
                ('accounttype', models.CharField(max_length=20)),
                ('accamt', models.IntegerField()),
            ],
        ),
    ]
